version: '3.3'
services:
  mongodb:
    container_name: keycloakpoc_mongo
    image: mongo
    networks:
      - app_network
  keycloak:
    container_name: keycloakpoc_keycloakserver
    image: jboss/keycloak
    ports:
      - "8180:8180"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    command:
      -Djboss.bind.address=0.0.0.0
      -Djboss.http.port=8180
    networks:
      - app_network
  webapp:
    container_name: keycloak_web
    image: keycloak-poc
    links:
      - mongodb
      - keycloak
    networks:
      - app_network
    environment:
      - KEYCLOAK_PORT=8180
    ports:
      - "8080:8080"

networks:
  app_network:
    driver: bridge