version: '3.3'
services:
  mongodb:
    container_name: keycloakpoc_mongo
    image: mongo
    networks:
      - app_network
  keycloak:
    container_name: keycloakpoc_keycloakserver
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    networks:
      - app_network
  webapp:
    container_name: keycloack_web
    image: keycloak-poc
    links:
      - mongodb
      - keycloak
    networks:
      - app_network
    ports:
      - "8180:8180"

networks:
  app_network:
    driver: bridge